# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e757b0ae16ff11fa82af2f75cc2fef102cfab02ed2d5d60ce74c71b2e3974fe35230b323b1e1c68b3688e838f51efdca21d8b66cd404de47f4f75ac1e3277395

test:
  secret_key_base: a853f2975ed9efeaf628dc6201707d6fb86255acab699aa0b3ef249a7bb4bf689cd915ca62d1a970dab7d75f7b26dcc0085e49e638bcd7b414c97836f074f87a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
